site_name: SICK Sensor Starter Kits
site_url: https://sickag.github.io/SICK-Sensor-Kits
use_directory_urls: false
nav:
  - Home: index.md
  - Vision Sensor Kit: 
    - Overview: vision/vision_overview.md
    - Getting Started: vision/vision_getting_started.md
    - Code Snippets: vision/vision_code_snippets.md
    - Advanced: vision/vision_advanced.md
    - Example Projects: 
      - Overview: vision/vision_example_projects.md
      - Classify Hex Nuts/Screws: vision/classify_hex_nuts_screws.md
      - Sketch Demonstrator: vision/sketch_demonstrator.md
      - Chocolate Inspection: vision/chocolate_inspection.md
      - Rock, Paper, Scissors: vision/rock_paper_scissors.md
    - Training Material: vision/vision_training_material.md
    - FAQ: vision/vision_faq.md
  - LiDAR Sensor Kit: 
    - Overview: lidar/lidar_overview.md
    - Getting Started: lidar/lidar_getting_started.md
    - Code Snippets: lidar/lidar_code_snippets.md
    - Advanced: lidar/lidar_advanced.md
  - IO-Link Connectivity Starter Kit: 
    - Overview: iolink/iolink_overview.md
    - Getting Started: iolink/iolink_getting_started.md
    - Code Snippets: iolink/iolink_code_snippets.md
    - Advanced: iolink/iolink_advanced.md
    - Example Projects:
      - Overview: iolink/iolink_example_projects.md
      - SensorFusion: iolink/sensor_fusion.md
    - Training Material: iolink/iolink_training_material.md
  - FAQ: faq.md
  - Imprint: https://www.sick.com/de/de/s/imprint

theme:
  language: en
  name: material
  palette:
    primary: custom
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/sick_logo.png'
  features:
    - content.code.copy
  favicon: 'images/favicon.ico'
extra_css:
  - stylesheets/extra.css
copyright: "Â© SICK AG 2025"
plugins:
  - mkdocs-video

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true